// mod old;

mod analytics;
mod answer;
mod api_key_chain;
mod api_key_extraction;
mod batch_get_documents;
mod boost_integration;
mod bugs;
mod claim_limitations;
mod commit;
mod concurrency;
mod customer_jwt_search;
mod delete_doc;
mod entity_lifecycle;
mod facets;
mod filter;
mod filter_benchmark;
mod fulltext_benchmark_test;
mod fulltext_search;
mod geosearch;
mod groupby;
mod hook_transform_after_search;
mod hook_transform_before_save;
mod hooks;
mod values;
// mod hurl;
mod index_rebuild;
mod list_documents;
mod mcp_server;
mod multi_index;
mod omc_test;
mod openai_chat;
mod pin_rules;
mod quick_fulltext_benchmark;
mod regenerate_read_api_key;
mod replace_doc_on_insert;
mod replace_index;
mod replace_index_bool_promotion;
mod replace_index_date_promotion;
mod replace_index_geopoint_promotion;
mod replace_index_number_promotion;
mod replace_index_string_filter_promotion;
mod replace_index_string_promotion;
mod shelves;
mod shutdown;
mod sort;
mod suggestions;
mod temp_index;
mod temp_index_cleanup;
mod update_docs;
mod vector_search;

pub mod utils;
