// mod old;

mod answer;
mod api_key_chain;
mod bugs;
mod commit;
mod concurrency;
mod delete_doc;
mod entity_lifecycle;
mod facets;
mod filter;
mod filter_benchmark;
mod fulltext_benchmark_test;
mod fulltext_search;
mod geosearch;
mod hooks;
mod quick_fulltext_benchmark;
// mod hurl;
mod index_rebuild;
mod list_documents;
mod migrations;
mod offload_field;
mod replace_doc_on_insert;
mod replace_index;
mod shutdown;
mod sort;
mod suggestions;
mod temp_index;
mod temp_index_cleanup;
mod update_docs;
mod vector_search;

pub mod utils;
