{
 "title": "OramaCore",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "quantile", "label": "Quantile", "query": { "query": "label_values(quantile)" } }
  ]
 },
 "panels": [
  {
   "title": "Matching document",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "matching_percentage_calculation_count{quantile=\"$quantile\"}",
     "legendFormat": "__auto"
    },
    { "expr": "matching_calculation_count_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Search time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "search_calculation_time_sec{quantile=\"$quantile\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "filter_calculation_time_sec{quantile=\"$quantile\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "operation_count{quantile=\"$quantile\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Field indexing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "writer_field_calculation_time_sec{quantile=\"$quantile\", field_type!=\"embedding\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "field_commit_calculation_time_sec{quantile=\"$quantile\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "document_commit_calculation_time_sec{quantile=\"$quantile\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}